export default function App() {
    return (
        <>
              {/* HERO */}
                    <section className="hero">
                            <div className="hero-content">
                                      <span className="badge">Ente riconosciuto Regione Calabria</span>
                                                <h1>Costruisci il tuo futuro professionale</h1>
                                                          <p>
                                                                      Corsi di formazione pensati per aiutarti a crescere, acquisire competenze
                                                                                  e cogliere nuove opportunità lavorative.
                                                                                            </p>
                                                                                                      <button className="cta-primary">Richiedi informazioni gratuite</button>
                                                                                                              </div>
                                                                                                                    </section>

                                                                                                                          {/* ISTITUZIONALE */}
                                                                                                                                <section className="section">
                                                                                                                                        <h2>Chi siamo</h2>
                                                                                                                                                <p className="section-text">
                                                                                                                                                          <strong>Associazione C.E.I.O</strong> è un ente di formazione riconosciuto dalla
                                                                                                                                                                    Regione Calabria. Operiamo sul territorio con percorsi formativi
                                                                                                                                                                              orientati allo sviluppo delle competenze e all’inclusione lavorativa.
                                                                                                                                                                                      </p>

                                                                                                                                                                                              <div className="info-grid">
                                                                                                                                                                                                        <div>📍 Via Brutium 16 – Catanzaro (CZ)</div>
                                                                                                                                                                                                                  <div>📄 P. IVA 04039860798</div>
                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                </section>

                                                                                                                                                                                                                                      {/* PROGRAMMI */}
                                                                                                                                                                                                                                            <section className="section light">
                                                                                                                                                                                                                                                    <h2>I nostri programmi di formazione</h2>

                                                                                                                                                                                                                                                            <div className="cards">
                                                                                                                                                                                                                                                                      <div className="card">
                                                                                                                                                                                                                                                                                  <h3>SFL</h3>
                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                            Supporto per la Formazione e il Lavoro: percorsi formativi per
                                                                                                                                                                                                                                                                                                                          migliorare le competenze e favorire l’inserimento lavorativo.
                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                  <button>Verifica i requisiti</button>
                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                      <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                  <h3>ADI</h3>
                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                            Assegno di Inclusione: formazione e accompagnamento per
                                                                                                                                                                                                                                                                                                                                                                                                                          l’inclusione sociale e professionale.
                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button>Scopri di più</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="card">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <h3>Programma GOL</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Percorsi personalizzati di aggiornamento e riqualificazione
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          professionale.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button>Accedi al programma</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {/* PERCHÉ NOI */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <section className="section">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <h2>Perché scegliere C.E.I.O</h2>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="features">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div>✅ Ente riconosciuto dalla Regione Calabria</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <div>✅ Percorsi formativi orientati al lavoro</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <div>✅ Tutoraggio e supporto costante</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div>✅ Formazione accessibile e finanziata</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div>✅ Presenza sul territorio</div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {/* CTA FINALE */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <section className="cta">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <h2>Inizia oggi il tuo percorso di formazione</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Contattaci per ricevere informazioni e scoprire quale percorso è più
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      adatto a te.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button className="cta-primary">Contattaci ora</button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </section>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {/* FOOTER */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <strong>Associazione C.E.I.O</strong><br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Ente di formazione riconosciuto dalla Regione Calabria<br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                Via Brutium 16 – Catanzaro (CZ) 88100<br />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        P. IVA 04039860798
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </footer>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
}